services:
  rtmp-server:
    image: tiangolo/nginx-rtmp
    ports:
      - 1935:1935
      - 8080:80
    environment:
      - NGINX_PORT=80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static/stat.xsl:/var/local/stat.xsl
